In [1]:
 import pandas as pd

In [19]:
cleaned_reports = pd.read_csv('data/cleaned_reports.csv')
cleaned_reports = cleaned_reports[['Sentence','cleaned_text','Year']]
cleaned_reports

,Sentence,cleaned_text,Year
0,Foreword Enabling sustainability for our compa...,foreword enabling sustainability company custo...,2022
1,"Extreme weather caused devastating droughts, w...",extreme weather caused devastating droughts wi...,2022
2,We felt the effects of climate change like nev...,felt effects climate change like never planet ...,2022
3,The most recent report from the Intergovernmen...,recent report intergovernmental panel climate ...,2022
4,Meaningful climate action requires an enduring...,meaningful climate action requires enduring co...,2022
...,...,...,...
9614,Microsofts diversity education programs provid...,microsofts diversity education programs provid...,2003
9615,Businesses Microsoft sponsors a variety of pro...,businesses sponsors variety programs designed ...,2003
9616,"Since its inception, the national awardwinning...",since inception national awardwinning build bu...,2003
9617,"At Microsoft, our commitment to diversity goes...",commitment diversity goes beyond recruiting em...,2003
9618,Its a vital component of our ongoing mission: ...,vital component ongoing mission enable people ...,2003

In [20]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

# Download the VADER lexicon
nltk.download('vader_lexicon')

# Initialize the VADER sentiment analyzer
sia = SentimentIntensityAnalyzer()
# Apply VADER to each text and store the compound score
cleaned_reports['vader_score'] = cleaned_reports['Sentence'].apply(lambda text: sia.polarity_scores(text)['compound'])

cleaned_reports

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/macbookair/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

,Sentence,cleaned_text,Year,vader_score
0,Foreword Enabling sustainability for our compa...,foreword enabling sustainability company custo...,2022,0.0000
1,"Extreme weather caused devastating droughts, w...",extreme weather caused devastating droughts wi...,2022,-0.7003
2,We felt the effects of climate change like nev...,felt effects climate change like never planet ...,2022,0.2500
3,The most recent report from the Intergovernmen...,recent report intergovernmental panel climate ...,2022,-0.5106
4,Meaningful climate action requires an enduring...,meaningful climate action requires enduring co...,2022,0.8519
...,...,...,...,...
9614,Microsofts diversity education programs provid...,microsofts diversity education programs provid...,2003,0.5574
9615,Businesses Microsoft sponsors a variety of pro...,businesses sponsors variety programs designed ...,2003,0.7096
9616,"Since its inception, the national awardwinning...",since inception national awardwinning build bu...,2003,0.6908
9617,"At Microsoft, our commitment to diversity goes...",commitment diversity goes beyond recruiting em...,2003,0.3818
9618,Its a vital component of our ongoing mission: ...,vital component ongoing mission enable people ...,2003,0.2960

In [21]:
cleaned_reports.dropna(subset=['cleaned_text'], inplace=True)

In [22]:
has_nulls = cleaned_reports['cleaned_text'].isnull().any()
print("Are there any null values in 'cleaned_text'?", has_nulls)

Are there any null values in 'cleaned_text'? False

In [23]:
from joblib import dump, load
loaded_model = load('models/voting_classifier_model.joblib')
print("Model loaded")
loaded_vectorizer = load('models/tfidf_vectorizer.joblib')
print("Vecotrizer loaded")

# Transform the text data using the loaded vectorizer
transformed_texts = loaded_vectorizer.transform(cleaned_reports['cleaned_text'])

Model loaded
Vecotrizer loaded

In [24]:
# Get predictions
predictions = loaded_model.predict(transformed_texts)

In [25]:
# Add predictions to the DataFrame
cleaned_reports['predicted_class'] = predictions
cleaned_reports

,Sentence,cleaned_text,Year,vader_score,predicted_class
0,Foreword Enabling sustainability for our compa...,foreword enabling sustainability company custo...,2022,0.0000,Social
1,"Extreme weather caused devastating droughts, w...",extreme weather caused devastating droughts wi...,2022,-0.7003,Environmental
2,We felt the effects of climate change like nev...,felt effects climate change like never planet ...,2022,0.2500,Environmental
3,The most recent report from the Intergovernmen...,recent report intergovernmental panel climate ...,2022,-0.5106,Environmental
4,Meaningful climate action requires an enduring...,meaningful climate action requires enduring co...,2022,0.8519,Environmental
...,...,...,...,...,...
9614,Microsofts diversity education programs provid...,microsofts diversity education programs provid...,2003,0.5574,Social
9615,Businesses Microsoft sponsors a variety of pro...,businesses sponsors variety programs designed ...,2003,0.7096,Social
9616,"Since its inception, the national awardwinning...",since inception national awardwinning build bu...,2003,0.6908,Social
9617,"At Microsoft, our commitment to diversity goes...",commitment diversity goes beyond recruiting em...,2003,0.3818,Social
9618,Its a vital component of our ongoing mission: ...,vital component ongoing mission enable people ...,2003,0.2960,Social

In [26]:
cleaned_reports = cleaned_reports[cleaned_reports['predicted_class'] != 'General']
cleaned_reports

,Sentence,cleaned_text,Year,vader_score,predicted_class
0,Foreword Enabling sustainability for our compa...,foreword enabling sustainability company custo...,2022,0.0000,Social
1,"Extreme weather caused devastating droughts, w...",extreme weather caused devastating droughts wi...,2022,-0.7003,Environmental
2,We felt the effects of climate change like nev...,felt effects climate change like never planet ...,2022,0.2500,Environmental
3,The most recent report from the Intergovernmen...,recent report intergovernmental panel climate ...,2022,-0.5106,Environmental
4,Meaningful climate action requires an enduring...,meaningful climate action requires enduring co...,2022,0.8519,Environmental
...,...,...,...,...,...
9614,Microsofts diversity education programs provid...,microsofts diversity education programs provid...,2003,0.5574,Social
9615,Businesses Microsoft sponsors a variety of pro...,businesses sponsors variety programs designed ...,2003,0.7096,Social
9616,"Since its inception, the national awardwinning...",since inception national awardwinning build bu...,2003,0.6908,Social
9617,"At Microsoft, our commitment to diversity goes...",commitment diversity goes beyond recruiting em...,2003,0.3818,Social
9618,Its a vital component of our ongoing mission: ...,vital component ongoing mission enable people ...,2003,0.2960,Social

In [27]:

yearly_category_avg_score = cleaned_reports.groupby(['Year', 'predicted_class']).vader_score.mean().reset_index()

print("Average Daily Sentiment:")
yearly_category_avg_score

Average Daily Sentiment:

    Year predicted_class  vader_score
0   2003   Environmental    -0.026744
1   2003      Governance     0.253578
2   2003          Social     0.445030
3   2005   Environmental     0.279450
4   2005      Governance     0.519736
5   2005          Social     0.482264
6   2006   Environmental     0.438680
7   2006      Governance     0.263533
8   2006          Social     0.500849
9   2007   Environmental     0.359280
10  2007      Governance     0.210750
11  2007          Social     0.518255
12  2010   Environmental     0.376140
13  2010      Governance     0.328150
14  2010          Social     0.440654
15  2011   Environmental     0.355380
16  2011      Governance     0.118046
17  2011          Social     0.468392
18  2012   Environmental     0.439455
19  2012      Governance     0.262200
20  2012          Social     0.445918
21  2013   Environmental     0.399802
22  2013      Governance     0.222333
23  2013          Social     0.417180
24  2014   Environmental     0.286816
25  2014      Governance     0.339159
26  2014          Social     0.426923
27  2015   Environmental     0.347465
28  2015      Governance     0.374143
29  2015          Social     0.428643
30  2016   Environmental     0.398221
31  2016      Governance     0.451824
32  2016          Social     0.418245
33  2017   Environmental     0.367027
34  2017      Governance     0.208300
35  2017          Social     0.440468
36  2018   Environmental     0.294646
37  2018      Governance     0.417920
38  2018          Social     0.435155
39  2019   Environmental     0.384153
40  2019          Social     0.461428
41  2020   Environmental     0.302776
42  2020          Social     0.388053
43  2021   Environmental     0.241842
44  2021      Governance     0.279383
45  2021          Social     0.390002
46  2022   Environmental     0.299806
47  2022      Governance     0.064000
48  2022          Social     0.414319

In [28]:
yearly_category_avg_score.to_csv('data/ESG_reports_scores.csv')